from .util_types import Channel, TimeTag

from .ptu_parser import parse, Parser
from .coincidence_counter import CoincidenceCounter
from .calc_g2 import calc_g2
from .device import Device, DeviceConfig, DeviceInputChannelConfig, list_device_index

from multiharp_toolkit._mhtk_rs import (
    Mode,
    RefSource,
    Edge,
    MeasurementControl,
    get_library_version,
    open_device,
    close_device,
    initialize,
    get_hardware_info,
    get_feature,
    get_serial_number,
    get_base_resolution,
    get_number_of_input_channels,
    get_number_of_modules,
    get_module_info,
    get_debug_info,
    set_sync_divider,
    set_sync_edge_trigger,
    set_sync_channel_enable,
    set_sync_channel_offset,
    set_sync_deadtime,
    set_input_edge_trigger,
    set_input_channel_offset,
    set_input_channel_enable,
    set_input_deadtime,
    set_input_hysteresis,
    set_stop_overflow,
    set_binning,
    set_offset,
    set_histogram_length,
    clear_histogram_memory,
    set_measurement_control,
    set_trigger_output,
    start_measurement,
    stop_measurement,
    ctc_status,
    get_histogram,
    get_all_histograms,
    get_resolution,
    get_sync_rate,
    get_count_rate,
    get_all_count_rates,
    get_flags,
    get_elapsed_measurement_time,
    get_start_time,
    get_warnings,
    read_fifo,
    is_measurement_running,
)
